package org.presentation;

import javax.swing.*;

public class Administrator {
    private JTabbedPane tabbedPane1;
    private JPanel BusquedaPanel;
    private JTextField nombreFld;
    private JButton buscarButton;
    private JButton ImprimirButton;
    private JTextField idFld;
    private JLabel ID;
    private JTextField idfuncionarios;
    private JLabel Nombre;
    private JTextField nombreFuncionarios;
    private JTextField telefono;
    private JButton guardarButton;
    private JButton borrarButton;
    private JButton limpiarButton;
    private JTable table1;
    private JTextField fechaFld;
    private JButton button1;
    private JComboBox categoriaComboBox;
    private JButton cargarButton;
    private JButton imprimirButton;
    private JTextField desdeFld;
    private JTextField hastaFld;
    private JButton button2;
    private JTextField desdeAFld;
    private JButton button3;
    private JTextField hastaAFld;
    private JButton cargarButtonA;
    private JTable table2;
    private JTextField descripcionFld;
    private JButton buscarButton1;
    private JButton imprimirButton1;
    private JTextField IDfld;
    private JTextField DescripcionFld2;
    private JButton guardarButton1;
    private JButton borrarButton1;
    private JButton limpiarButton1;
    private JTable table3;
    private JComboBox comboBox1;
    private JTextField DescripcionFld;
    private JButton imprimirButton2;
    private JButton buscarButton2;
    private JTextField idfld;
    private JTextField Descripcionfld2;
    private JComboBox categoriacombobox;
    private JButton button4;
    private JButton button5;
    private JButton button6;
}
